config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  resources :weather_grid
 

  get "/subscriptions/cancel_subscription"  => "subscriptions#cancel_subscription"
  get "/subscriptions/update_card"          => "subscriptions#update_card"
  post "/subscriptions/update_card_details" => "subscriptions#update_card_details"
  resources :subscriptions

  mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

  root to: "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index 
		@message = "Welcome user"
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user.nil? %>
    
    <% if request.subdomain.blank? || request.subdomain == "www" %>
        <%= link_to('Sign up', new_user_registration_path) %>    
        <br>
    <% else %>
        <%= link_to('Login', new_user_session_path) %>
        <br>
    <% end %>  
        
    <% else %>
    	Welcome <%= current_user.email %>
    	<br>
    	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
       
            <%= link_to('Manage Subscriptions', subscriptions_path) %>  
        
    <% end %>       
    <br>
    <% unless current_user.nil? %>
        <% if current_user.has_role? :app_admin%>
            <%= link_to('Invite User', new_user_invitation_path) %>  
        <% end %>  
    <% end %>

    <h4><%= @message %> </h4>